main: prepare_jourdan_grok get_jourdan_grok

prepare_jourdan_grok:
	mkdir -p ./src
	mkdir -p ./doc
	mkdir -p ./distr

get_jourdan_grok:
	# wget -c https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/semicomplete/source-archive.zip -O ./src/source-archive.zip
	#git clone https://github.com/jordansissel/grok.git ./src
	git pull ./src

.PHONY: main
