main: prepare_semi get_semi

prepare_semi:
	mkdir -p ./src
	mkdir -p ./doc
	mkdir -p ./distr

get_semi:
	wget -c https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/semicomplete/source-archive.zip -O ./src/source-archive.zip


.PHONY: main
